### ISSUE TITLE
Create simple map chart using harcoded data

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/simplechart#1]
We want to explore which data is needed, how it works.

Create it using the latest stable d3js version.

Assigned to ctorres (pending invite).

**Comment by brauliodiez** [comment]
Hi Carlos can you paste the URL of your spike repo?

**Comment by carlostxm** [comment]
Sure, https://carlostxm.github.io/d3-map-chart/

And this is the repo
https://github.com/carlostxm/d3-map-chart
