### ISSUE TITLE
Move seed project from standard react / react router to nextjs allowing serverside rendering

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/simplechart#26]
Steps:

- Understand how nextjs works:
   - Take a look to the concepts post: http://lemoncode.net/lemoncode-blog/2018/5/13/server-side-rendering-i-conceptos
   - Check the step by step sample guide: https://github.com/Lemoncode/nextjs-typescript-by-sample
   - Check the nextjs tutorial: https://nextjs.org/learn/
   - [coming soon] Check the second part of the post (Server side rendering)

- Update dependencies on the project to the latests available, check that everything works.
- Remove react router dependencies.
- Add nextjs structure, plus pages.
- Check that everything is working as expected and that server side rendering is triggered when needed.

**Comment by PedroJesusRomeroOrtega** [comment]
Hello!
I'm migrating to **Nextjs** in this [fork](https://github.com/PedroJesusRomeroOrtega/simplechart/tree/migrate_to_nextjs).

I have a console.error with **React-hot-loader** _It appears that "react-hot-loader/patch" did not run immediately before the app started_
While trying to fix this I read that **WebPack** has it's own [HMR](https://webpack.js.org/guides/hot-module-replacement/), so it's necessary to use **ReactHotLoader**?

Other question.
_index.html_ is necessary?
With **Nextjs** I can´t use _ReactDOM.render_
```
const render = (Component) => {
  ReactDOM.render(
    <AppContainer>
      <Component/>
    </AppContainer>,
    document.getElementById('root'),
  );
};
```
so I replace it with
```
const index = () => (
  <AppContainer>
    <App />
  </AppContainer>
);
export default index;
```
I'm not sure how I can do `document.getElementById('root')`

Thank you.

**Comment by brauliodiez** [comment]
About react-hot-loader and wepack, since we stick to next, it provides all that we need, if we need to extend it we will need tu use netx.merge

Index.html won't be in use, tha't great

Next provides it's own way to move forward we have to stick with it

Good progress !!
