### ISSUE TITLE
Create a simple line chart using d3js with harcoded data

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/simplechart#4]
We want to explore which data is needed, how it works.

Create it using the latest stable d3js version.

**Comment by juanbermudezpareja** [comment]
In next repository, you can find a multiline chart that uses d3 v4:
[Multiline chart sample](https://github.com/juanbermudezpareja/LineChartReact)
It could be configured using one of these possible data inputs:
- Hardcoded data
- CSV file
- TSV file

Published using gh-pages here:
https://juanbermudezpareja.github.io/LineChartReact/

**Comment by brauliodiez** [comment]
Really good stuff, congrats
