### ISSUE TITLE
Gauge chart

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/simplechart#6]
Entry point (d3 v2)

http://bl.ocks.org/msqr/3202712

Steps:
  - Understand the code.
  - Refactor to something more understandable
  - Port to to v4

Assigned to @adrigardi90

**Comment by adrigardi90** [comment]
Simple Gauge Chart with React and d3 (v4) on the following repo:

https://github.com/adrigardi90/simplechart/tree/Simple_Chart_Development
